Repository Counselllor/Counsellor-Web, pull requests merged in 2023-08, with the labels that each got.

#305 {GSSoC'23} Adding Register Screen
  mobile/lib/login.dart
  mobile/lib/main.dart
  mobile/lib/register.dart
Labels: assigned, level3, priority: high

#312 Email validation add on forgot password form
  package-lock.json
  src/components/ForgotPassword/ForgotPassword.css
  src/components/ForgotPassword/ForgotPassword.jsx
Labels: gssoc23, assigned, level2, priority: medium

#321 Footer
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Login/Login.jsx
  src/components/SignUp/SignUp.jsx
  src/components/SignUp/Signup.css
Labels: gssoc23, assigned, level3, priority: high
