Repository Counselllor/Counsellor-Web, pull requests merged in 2024-07, with the labels that each got.

#832 responsive profile
  src/assets/avatar1.png
  src/assets/avatar2.png
  src/assets/avatar3.png
  src/assets/avatar4.png
  src/components/Dashboard/Dashboard.jsx
  src/components/Navbar/Navbar.jsx
  src/components/ProfileComponent/ProfileCard.css
  src/components/ProfileComponent/ProfileCard.jsx
Labels: gssoc, level3

#833 Added "Footer" in "Blogs" and "Our Contributors Page"
  src/components/Contributors/Contribute.jsx
  src/components/blogs/Blogs.jsx
Labels: gssoc, level2

#837 [Bug] : Text cannot visible
  src/components/Dashboard/Dashboard.css
Labels: gssoc, level3

#840 Added the Career Support page
  src/components/Career Support/CareerSupport.css
  src/components/Career Support/CareerSupport.jsx
  src/components/Dashboard/Dashboard.jsx
  src/index.jsx
Labels: gssoc, level3

#825 Fixed many Errors and also included some features
  package.json
  src/components/Contributors/Contribute.css
  src/components/Contributors/Contribute.jsx
  src/components/Courses/Courses.css
  src/components/Courses/Courses.jsx
  src/components/Login/Login.jsx
  src/index.css
Labels: gssoc, level3

#853 fixed the college cards by adding proper responsiveness
  src/components/Dashboard/Dashboard.css
  src/components/Dashboard/Dashboard.jsx
  src/components/Navbar/Navbar.css
Labels: gssoc, assigned, level3

#881 Added techstack change option
  src/components/Dashboard/Dashboard.jsx
  src/components/ProfileComponent/ProfileCard.css
  src/components/ProfileComponent/ProfileCard.jsx
  src/components/ProfileComponent/techstack.json
Labels: gssoc, level3

#861 Enhanced Blog page
  src/components/Navbar/Navbar.jsx
  src/components/blogs/Blogs.css
  src/components/blogs/Blogs.jsx
Labels: gssoc, level3

#845 [Feature] : Resposive Nav Bar
  package-lock.json
  src/components/Dashboard/Dashboard.css
  src/components/Navbar/Navbar.css
Labels: gssoc, level2

#949 Added Links to The Website Logo in Navbar
  src/components/Courses/Courses.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Navbar/Navbar.jsx
  src/components/blogs/Blogs.jsx
Labels: gssoc, level2

#1025 Career Support Pg fixed
  src/components/Career Support/CareerSupport.jsx
Labels: gssoc, level2

#1083 Institute and student cards
  package-lock.json
  src/components/CollegePage/CollegePage.css
  src/components/CollegePage/CollegePage.jsx
Labels: gssoc, level3

#1175 Profile Page Redirect not Working #1156
  src/components/Profile/ProfileHeader.jsx
Labels: gssoc, level1

#1214 Want to Add Eye Icon in Signup Password field #1211
  src/components/SignUp/Signup.css
Labels: gssoc, level1

#1231 Fixing white line on left corner of the website everywhere #1224
  index.html
Labels: gssoc, level1

#1281 Enhanced the joinus page
  src/components/Joinus/JoinUs.jsx
  src/components/Joinus/Jointestimonial.css
  src/components/Joinus/Jointestimonial.jsx
  src/components/Joinus/Joinus.css
Labels: assigned, level3

#1293 Click More button Click issue #1288
  src/components/Dashboard/Dashboard.css
Labels: gssoc, level2
